### ISSUE TITLE
Feedback report does not correctly sum total points 

### ISSUE THREAD

**Issue by lwasser** [earthlab/autograding-notebooks#7]
@jlpalomino noted this notebook as an example of this issue:

https://github.com/earth-analytics-edu/assignment1-lherwehe/

Jenny can you add more specifics here to this issue. @kcranston do you need anything else to work on it?

**Comment by jlpalomino** [comment]
There appears to be an error in how the total number of points for the notebook is generated from the credit that is assigned to each cell. In [Lauren's example notebook](https://github.com/earth-analytics-edu/assignment1-lherwehe/blob/master/bootcamp-test-assignment.ipynb), we purposefully added a mistake, so that the last cell achieved only 13 out of 15 points. 

However, the [feedback report](https://github.com/earth-analytics-edu/assignment1-lherwehe/blob/master/feedback.html#L13201) assigned a score of 15 out of 15 points for that cell.

**Comment by kcranston** [comment]
This was not an nbgrader partial credit bug - it was an problem with the github scripts and some leftover files from previous testing. See [feedback report from Laruen's notebook](https://github.com/earth-analytics-edu/assignment1-lherwehe/blob/master/feedback.html), which now reports the correct score. Yay!
